# Generated by Django 4.2.2 on 2023-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subir_proyecto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subir_proyecto',
            name='repositorio',
            field=models.CharField(default='', max_length=100),
        ),
    ]
