# Generated by Django 4.2.2 on 2023-06-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_subir_proyecto_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
