# Generated by Django 4.2.2 on 2023-06-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuariocliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='ciudad',
            field=models.CharField(default='Ciudad Predeterminada', max_length=50),
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='numeracion',
            field=models.CharField(default='numeracion', max_length=10),
        ),
    ]
