# Generated by Django 4.2.2 on 2023-06-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuariocliente_ciudad_usuariocliente_numeracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
