# Generated by Django 4.2.2 on 2023-06-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_usuariocliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01', null=True),
        ),
    ]
