# Generated by Django 4.2.2 on 2023-06-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_usuariocliente_numeracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='correo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='numeracion',
            field=models.CharField(default='numeracion', max_length=10),
        ),
    ]
