# Generated by Django 4.2.2 on 2023-06-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_usuariocliente_numeracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='correo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
