# Generated by Django 4.2.2 on 2023-06-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_usuariocliente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='numeracion',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
