# Generated by Django 4.2.2 on 2023-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_usuariocliente_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocliente',
            name='fecha_nacimiento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='numeracion',
            field=models.CharField(default='0000', max_length=15),
        ),
    ]
